language: elixir
elixir:
  - 1.8.2
otp_release:
  - 22.0
sudo: false
env:
  - MIX_ENV=test
  - MIX_ENV=test ELIXIR_ERL_OPTIONS="+T 9"
before_install:
  - epmd -daemon
before_script:
  - mix compile --warnings-as-errors
  - mix dialyzer
script:
  - elixir --sname a -S mix coveralls.travis
  - mix dialyzer --halt-exit-status
  - mix credo --strict
after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
cache:
  directories:
    - .dialyxir
    - _build
    - deps
